### PR TITLE
Interlink the navigation bar in each part of the website. Change the …

### PR DESCRIPTION
**Pull request by elongateddmuskrat**
…color scheme in resources to match the rest of the website

### CODE REVIEW

**Comment by elongateddmuskrat** [comment]
Screen Shot 2020-07-19 at 11 01 53 AM
Screen Shot 2020-07-19 at 11 01 41 AM
Screen Shot 2020-07-19 at 11 00 01 AM

**Comment by elongateddmuskrat** [comment]
only aesthetic change is in the resources page, the only change in the events and sign in page is that the navigation bar is clickable now

**Comment by justness** [comment]
Could you please make the aesthetics of the navigation bar consistent across pages?

**Comment by elongateddmuskrat** [comment]
@justness @jamilao @ewu48 

Screen Shot 2020-07-19 at 2 09 11 PM
Screen Shot 2020-07-19 at 2 09 30 PM
Screen Shot 2020-07-19 at 2 09 17 PM

**Pull request merged**
